### ISSUE TITLE
Not able to pass label options to differential via \doptions

### ISSUE THREAD

**Issue by idlaviV** [hoodmane/spectralsequences#4]
Hi,

I propably got something wrong, but the following code does not what I want it to do:
[example.txt](https://github.com/hoodmane/spectralsequences/files/3652749/example.txt) (MWE)
I wanted to have and print a spectral sequence and then print it again, but with an additional label at a differential (usecase: revealing stuff in a beamerfile).

Changing the color of the differential and label works, but passing a labeltext to the differential via \doptions does not seem to have an effect. Although the manual says, that the universal options in 4.1 could be used with \doptions.

What do I do wrong?

Thanks anyways for the great package! I love it!

**Comment by hoodmane** [comment]
Seems like a bug. I'll investigate and hopefully get you a fix soon. I vaguely remember that there was a problem with this before.

**Comment by hoodmane** [comment]
Okay, I believe that I fixed your issue. In order to use the fixed version, you'll need to download the copy of `sseqmain.code.tex` into your working directory. (I think this should suffice but it's possible that there are other changes to sseqmain that are incompatible with the current state of other files. In that case you might have to copy the whole repo into working directory).

**Comment by hoodmane** [comment]
Okay, I believe that I fixed your issue. In order to use the fixed version, you'll need to download the copy of `sseqmain.code.tex` into your working directory. (I think this should suffice but it's possible that there are other changes to sseqmain that are incompatible with the current state of other files. In that case you might have to copy the whole repo into working directory).

**Comment by idlaviV** [comment]
Wow, nice, works for me. Thanks!
